name: Deploy Workflow

# TRIGGERS
on:
  push:
    branches:
      # - deploy/*
      - main

# ENVIRONMENT VARIABLES
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  BRANCH_NAME: ${{ github.head_ref || github.ref }}

# CI/CD STEPS
jobs:
  deploy:
    name: Deploy to [docs.dxup.dev]
    runs-on: ubuntu-latest
    # needs: [build]
    if: always() && !cancelled() && !failure() && contains(github.ref, 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get a latest release tag
        run: echo LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`) >> $GITHUB_ENV

      - name: Deploy with DXUP
        uses: 'digitopvn/diginext-actions@v1.10'
        with:
            api_key: ${{ secrets.DX_API_KEY }}
            cluster: dxupprod
            registry: digitopdockerhub
            deploy_env: prod
            port: 3001
            tail: true

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "[DOCS.DXUP.DEV] Version ${{ env.LATEST_TAG }} has been deployed!"