name: Deploy Workflow

# TRIGGERS
on:
  push:
    branches:
      # - deploy/*
      - main

# ENVIRONMENT VARIABLES
env:
  GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
  BRANCH_NAME: ${{ github.head_ref || github.ref }}

# CI/CD STEPS
jobs:
  deploy:
    name: Deploy to [docs.diginext.site]
    runs-on: ubuntu-latest
    # needs: [build]
    if: always() && !cancelled() && !failure() && contains(github.ref, 'main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Deploy to DXUP
        uses: digitopvn/diginext-actions@v0
        with:
          dx_version: 3.21.2-prerelease.7
          workspace_url: https://topgroup-v2.diginext.site
          api_key: ${{ secrets.DX_API_KEY }}
          cluster: digitop-cluster
          registry: digitopdockerhub
          deploy_env: prod
          port: "3001"